In [1]:
import numpy as np
import pandas as pd

# Introduction

Procedures to be used

In [13]:
# outcome of one coin flip
np.random.randint(2)

0

In [14]:
# outcomes of ten thousand coin flips
np.random.randint(2, size=10000)

array([1, 1, 0, ..., 0, 0, 0])

In [15]:
# mean outcome of ten thousand coin flips
np.random.randint(2, size=10000).mean()

0.5022

In [16]:
# outcome of one coin flip
np.random.choice([0, 1])

1

In [17]:
# outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000)

array([0, 0, 0, ..., 0, 1, 1])

In [18]:
# mean outcome of ten thousand coin flips
np.random.choice([0, 1], size=10000).mean()

0.5013

In [20]:
# outcomes of ten thousand biased coin flips
np.random.choice([0, 1], p=[0.7, 0.3], size=10000)

array([1, 1, 0, ..., 0, 1, 0])

In [21]:
# mean outcome of ten thousand biased coin flips
np.random.choice([0, 1], p=[0.7, 0.3], size=10000).mean()

0.3035

# Probability Quiz

In this quiz, you will simulate coin flips and die rolls to compute proportions for the following outcomes.

* Two fair coin flips produce exactly two heads
* Three fair coin flips produce exactly one head
* Three biased coin flips with P(H) = 0.6 produce exactly one head
* A die rolls an even number
* Two dice roll a double
* Then, you'll compare these proportions with probabilities in the quizzes below.

When simulating coin flips, use 0 to represent heads and 1 to represent tails. When simulating die rolls, use the correct integers to match the numbers on the sides of a standard 6 sided die.



### 1. Two fair coin flips produce exactly two heads

In [32]:
# simulate 1 million tests of two fair coin flips
tests= np.random.randint(2, size=(1000000, 2))

# sums of all tests
tests_sum = tests.sum(axis=1)

# proportion of tests that produced exactly two heads
(tests_sum==0).mean()

0.25054

### 2. Three fair coin flips produce exactly one head

In [33]:
# simulate 1 million tests of three fair coin flips
tests= np.random.randint(2, size=(1000000, 3))

# sums of all tests
tests_sum = tests.sum(axis=1)

# proportion of tests that produced exactly one head
(tests_sum==2).mean()

0.374986

### 3. Three biased coin flips with P(H) = 0.6 produce exactly one head

In [35]:
# simulate 1 million tests of three bias coin flips
# hint: use np.random.choice()
tests = np.random.choice([0, 1], p=[0.6, 0.4], size=(1000000, 3))

# sums of all tests
tests_sum = tests.sum(axis=1)

# proportion of tests that produced exactly one head
(tests_sum==2).mean()

0.288714

### 4. A die rolls an even number

In [36]:
# simulate 1 million tests of one die roll
tests = np.random.randint(1, 7, size=int(1e6))

# proportion of tests that produced an even number
np.isin(tests, [2, 4, 6]).mean()

0.499839

### 5. Two dice roll a double

In [37]:
# simulate the first million die rolls
dice_1 = np.random.randint(1, 7, size=int(1e6))

# simulate the second million die rolls
dice_2 = np.random.randint(1, 7, size=int(1e6))

# proportion of tests where the 1st and 2nd die rolled the same number
(dice_1 == dice_2).mean()

0.166784