## KNN with Iris Dataset

In [1]:
# import libraries
import pandas as pd
import numpy as np
from sklearn import datasets
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import confusion_matrix, classification_report

In [2]:
# load iris dataset from sklearn
iris = datasets.load_iris()

In [3]:
iris_df = pd.DataFrame(np.c_[iris['data'], iris['target']], columns=[iris['feature_names'] + ['target']])
iris_df.head()

sepal length (cm) sepal width (cm) petal length (cm) petal width (cm) target
0               5.1              3.5               1.4              0.2    0.0
1               4.9              3.0               1.4              0.2    0.0
2               4.7              3.2               1.3              0.2    0.0
3               4.6              3.1               1.5              0.2    0.0
4               5.0              3.6               1.4              0.2    0.0

In [4]:
X = iris_df.iloc[:, :-1]
y = iris_df.iloc[:, -1]

In [5]:
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2)

In [6]:
ss = StandardScaler()
ss.fit(X_train)

X_train = ss.transform(X_train)
X_test = ss.transform(X_test)

In [7]:
knn = KNeighborsClassifier(n_neighbors=4)
knn.fit(X_train, y_train);

In [8]:
y_pred = knn.predict(X_test)

In [9]:
print(f"Classification Report: \n{classification_report(y_test, y_pred)}\n")
print(f"Confusion Matrix: \n{confusion_matrix(y_test, y_pred)}\n")

Classification Report: 
              precision    recall  f1-score   support

         0.0       1.00      1.00      1.00         7
         1.0       1.00      1.00      1.00        10
         2.0       1.00      1.00      1.00        13

    accuracy                           1.00        30
   macro avg       1.00      1.00      1.00        30
weighted avg       1.00      1.00      1.00        30


Confusion Matrix: 
[[ 7  0  0]
 [ 0 10  0]
 [ 0  0 13]]



In [10]:
y_pred

array([1., 1., 2., 2., 1., 2., 0., 2., 2., 2., 1., 2., 0., 1., 2., 1., 0.,
       2., 2., 0., 1., 2., 1., 0., 1., 2., 0., 2., 0., 1.])